# Generated by Django 3.1.4 on 2023-10-14 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('phone_number', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField()),
                ('complit', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=199)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='con',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usname', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cos_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=199)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.IntegerField(default=0)),
                ('tname', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerifiaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=4)),
                ('is_verfied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=100)),
                ('title', models.CharField(default='null', max_length=100)),
                ('model', models.CharField(default='null', max_length=100)),
                ('year', models.CharField(default='null', max_length=100)),
                ('rang', models.CharField(default='null', max_length=100)),
                ('phone_number', models.CharField(default='null', max_length=100)),
                ('email', models.CharField(default='null', max_length=100)),
                ('content', models.TextField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='null', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('counts', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('dis', models.CharField(max_length=399)),
                ('reward', models.IntegerField(default=0)),
                ('bill', models.IntegerField(default=0)),
                ('tname', models.CharField(default=0, max_length=399)),
                ('like', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('repost', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('ru', models.IntegerField(default=0)),
                ('address', models.CharField(default='undefined', max_length=1000)),
                ('mobile', models.IntegerField(default=0)),
                ('prouser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('image0', models.ImageField(upload_to='products/')),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(upload_to='products/')),
                ('image3', models.ImageField(upload_to='products/')),
                ('image4', models.ImageField(upload_to='products/')),
                ('sold', models.IntegerField(blank=True, default=1, null=True)),
                ('selling_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('selling_price1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('selling_price2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cos_category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=200)),
                ('mode', models.CharField(default='COD', max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('order_status', models.CharField(choices=[('Order Received', 'Order Received'), ('Order Processing', 'Order Processing'), ('On the way', 'On the way'), ('Order Completed', 'Order Completed'), ('Order Canceled', 'Order Canceled')], default='Order Received', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_complit', models.BooleanField(blank=True, default=False, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('reason', models.CharField(default='Others', max_length=100)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Filterpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protitle', models.CharField(max_length=200)),
                ('prodate', models.DateField(auto_now_add=True)),
                ('proimage', models.ImageField(upload_to='products/')),
                ('proimage1', models.ImageField(upload_to='products/')),
                ('proimage2', models.ImageField(upload_to='products/')),
                ('proimage3', models.ImageField(upload_to='products/')),
                ('proimage4', models.ImageField(upload_to='products/')),
                ('prosold', models.IntegerField(blank=True, default=1, null=True)),
                ('proselling_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('proselling_price1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('proselling_price2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('prodescription', models.TextField()),
                ('procategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cos_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('image0', models.ImageField(upload_to='products/')),
                ('sold', models.IntegerField(blank=True, default=1, null=True)),
                ('selling_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('selling_price1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('selling_price2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.cos_category')),
            ],
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
                ('product', models.ManyToManyField(to='shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.profile'),
        ),
    ]
