# Generated by Django 3.1.4 on 2023-10-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customerating',
            field=models.IntegerField(default=3),
        ),
    ]
