# Generated by Django 3.1.4 on 2023-10-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_review_customerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customerating',
            new_name='customerrating',
        ),
    ]
